# Exercise 1: Type conversions

In the lecture, we discussed the basic built-in data types: integers, floating-point numbers, booleans, and strings. Python allows us to convert one type to another using the following functions:

- [`int()`](https://docs.python.org/3/library/functions.html#int) converts its argument to an integer.
- [`float()`](https://docs.python.org/3/library/functions.html#float) converts its argument to a floating-point number. 
- [`bool()`](https://docs.python.org/3/library/functions.html#bool) converts its argument to a boolean.
- [`str()`](https://docs.python.org/3/library/stdtypes.html#str) converts its argument to a string.

These conversions mostly work in an intuitive fashion, with some exceptions. Perform the following tasks to see how they work in detail:

1.  Define a string variable `s` with the value `'1'`. Convert this variable to an integer, a float, and a boolean. Do you get the same behavior if you define the string `s` to be `'1.0'` instead?
2.  Define the string variables `s1`, `s2`, and `s3` with values `'True'`, `'False'`, and `''` (empty string), respectively. Convert each of these to a boolean. Can you guess the conversion rule?
3.  Define a floating-point variable `x` with the value `0.9`. Convert this variable to an integer, a boolean, and a string.
4.  Define the integer variables `i1` and `i2` with values `0` and `2`, respectively. Convert each of these variables to a boolean.
5.   Define the boolean variables `b1` and `b2` with values `True` and `False`, respectively. Convert each of them to an integer.
6.  NumPy arrays cannot be converted using `int()`, `float()`, etc. Instead, we have to use the 
    method [`astype()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html) 
    and pass the desired data type (e.g., `int`, `float`, `bool`) as an argument.

    Create a NumPy array called `arr` with elements `[0.0, 0.5, 1.0]` and convert it to an integer
    and a boolean type.


**# Task 1 - String Conversion Example**

In [ ]:
#1 string - 1
s = "1"
int(s)
float(s)
bool(s)

True

In [10]:
#1 string - 1.0
s = "1.0"
#Convert to integer
int(s)

ValueError: invalid literal for int() with base 10: '1.0'

In [11]:
#Convert to float
float(s)

1.0

In [ ]:
#Convert to boolean
bool(s)

True

**# Task 2 - Boolean**

In [14]:
#Define string variables
s1 = "True"
s2 = "False"
s3 = ""

In [17]:
#Converting to booleans
bool(s1)
bool(s2)
bool(s3)

False

**# Task 3 - Float conversion examples**

In [21]:
x = 0.9
int(x)
bool(x)
str(x)


'0.9'

**# Task 4 - Integer to Boolean**


In [23]:
i1 = 0
i2 = 2

bool(i1)
bool(i2)

True

**# Task 5 - Boolean to Integer**

In [29]:
b1 = True
b2 = False

int(b1)
int(b2)

0

**# Task 6 - NymPy arrays conversion**

In [30]:
import numpy as np

In [31]:
#Array as floating-point numbers
arr = np.array([0.0, 0.5, 1.0])

In [ ]:
#Convert to Integer
arr.astype(int)

array([0, 0, 1])

In [34]:
# Convert to Boolean
arr.astype(bool)

array([False,  True,  True])

***
# Exercise 2: Working with strings

Strings in Python are full-fledged objects, i.e., they contain both the character data as well as additional functionality implemented via functions or so-called _methods_.
The official [documentation](https://docs.python.org/3/library/stdtypes.html#string-methods) 
provides a comprehensive list of these methods. For our purposes, the most important are:

- [`str.lower()`](https://docs.python.org/3/library/stdtypes.html#str.lower) 
    and 
  [`str.upper()`](https://docs.python.org/3/library/stdtypes.html#str.upper)
  convert the string to lower or upper case, respectively.
- [`str.strip()`](https://docs.python.org/3/library/stdtypes.html#str.strip) 
  removes any leading or trailing whitespace characters from a string.
- [`str.count()`](https://docs.python.org/3/library/stdtypes.html#str.count)
  returns the number of occurrences of a substring within a string.
- [`str.startswith()`](https://docs.python.org/3/library/stdtypes.html#str.startswith) 
    and 
  [`str.endswith()`](https://docs.python.org/3/library/stdtypes.html#str.endswith) 
  check whether a string starts or ends with a given substring.

**Important:** These methods need to be applied to a particular string variable, not the class `str` itself. For example, if you have a string variable `s`, you use `s.lower()`, etc.

Moreover, strings are also sequences and as such support indexing in the 
same way as lists or tuples, so for example `'NHH'[1]` returns the 2nd character `'H'`.

In this exercise, you are asked to apply a few of these concepts.
Create a string variable with the value 
```python
s = '  NHH Norwegian School of Economics  '
```
and perform the following tasks:

1. Strip the surrounding spaces from the string using `strip()`.
2. Count the number of `'H'` in the string.
3. Modify your code so that it is case-insensitive, i.e., both instances of 
   `'h'` and `'H'` are counted.
4. Reverse the string, i.e., the last character should come first, and so on.
5. Create a new string which contains every 2nd letter from the original.
6. Select the last character from this new string using at least two different methods.


In [43]:
s = " NHH Norwegian School of Economics "

In [45]:
s.strip()

'NHH Norwegian School of Economics'

In [37]:
s.count("H")

2

In [39]:
s.lower().count("h")

3

In [40]:
s[::-1]

' scimonocE fo loohcS naigewroN HHN '

In [49]:
s = "Norwegian School of Economics"
s2 = s[::2]
s2

'NreinSho fEoois'

In [50]:
s2[-1]

's'

In [51]:
s2[len(s2)-1]

's'

***
# Exercise 3: Summing lists and arrays

In this exercise, we investigate an additional difference between built-in lists and NumPy arrays: performance.
You are asked to investigate performance differences for different implementations of the `sum()` function.

1. Create a list `lst` and a NumPy array `arr`, each of them containing the sequence 
   of ten values `0, 1, 2, ..., 9`.

   *Hint*: You can use the list constructor [`list()`](https://www.w3schools.com/python/ref_func_list.asp)
   and combine it with the [`range()`](https://docs.python.org/3/library/functions.html#func-range)
   function which returns an object representing a range of integers.

   *Hint:* You should create the NumPy array using 
   [`np.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html).

2. We want to compute the sum of integers contained in `lst` and `arr`. Use 
   the built-in function [`sum()`](https://www.w3schools.com/python/ref_func_sum.asp)
   to sum elements of a list.
   For the NumPy array, use the NumPy function 
   [`np.sum()`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html).

3. You are interested in benchmarking which summing function is faster.
    Repeat the steps from above, but use the cell magic 
    [`%timeit`](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit)
    to time the execution of a statement as follows:

    ```python
    %timeit statement
    ```

4.  Recreate the list and array to contain 100 integers starting from 0,
    and rerun the benchmark.

5.  Recreate the list and array to contain 10,000 integers starting from 0,
    and rerun the benchmark.


What do you conclude about the relative performance of built-in lists 
vs. NumPy arrays?

In [53]:
#Creating list
lst = list(range(10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
import numpy as np
#Create array
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Summing the two functions
sum(lst)

45

In [59]:
np.sum(arr)

np.int64(45)

In [60]:
#Benchmark with %timeit
%timeit sum(lst)

60.3 ns ± 2.32 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [61]:
%timeit np.sum(arr)

1.08 μs ± 2.47 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [63]:
# Repeat benchmark with 100 integers
N = 100
lst = list(range(N))
arr = np.arange(N)

In [64]:
%timeit sum(lst)

319 ns ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [65]:
%timeit sum(arr)

3.85 μs ± 89.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [71]:
#Repeat with 1000
N = 10000
lst = list(range(N))
arr = np.arange(N)

In [72]:
%timeit sum(lst)

27.1 μs ± 28.6 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [74]:
%timeit np.sum(arr)

1.95 μs ± 53.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
