# Control flow and list comprehensions

In this lecture, we continue to explore basic concepts
of the Python programming language such as
conditional execution and loops.

## Conditional execution

Frequently, we want to execute a code block only
if some condition holds. We can do this using the
`if` statement:

In [1]:
if 2*2 == 4:
    print('Python knows arithmetic!')

Python knows arithmetic!


A few observations:

-   Conditional blocks are grouped using indentation (leading spaces).
    Remember from the previous unit that whitespace matters in Python!
-   We write the equality operator using *two* equal signs,
    `==`. This is to distinguish it from the assignment operator `=`.

We can also add an `else` block that will be executed
whenever a condition is false:

In [2]:
if 2*2 == 3:
    # this branch will never be executed
    print('Something is fishy here')
else:
    print('Python knows arithmetic!')

Python knows arithmetic!


Finally, we can add more than one conditional branch
using the `elif` clause:

In [3]:
var = 1
if var == 0:
    print('var is 0')
elif var == 1:
    print('var is 1')
else:
    print('var is neither 0 nor 1')

var is 1


### Truth value testing
We already encountered `==` to test whether two values
are equal.
Python offers many more operators that return
either `True` or `False` and can be used to control conditional execution.

| Expression    | Description |
| ------------- | ----------- |
| `==`          | Equal. Works for numerical values, strings, etc. |
| `!=`          | Not equal. Works for numerical values, strings, etc. |
| `>`, `>=`,`<=`, `<` | Usual comparison of numerical values |
|  `a is b`, `a is not b`   | Test identity. `a is b` is `True` if `a` and `b` are the same object |
| `a in b`, `a not in b`    | Test whether `a` is or is not included in collection `b` |
| `if obj`, `if not obj`    | Most Python objects evaluate to `True` or `False` in an intuitive fashion (see below) |

Additionally, there are logical operators that
allow us to invert or combine two logical values:

| Expression | Description |
| ---------- | ----------- |
| `not a`    | Invert the logical value of `a` (`True` if `a` is `False`) |
| `a and b`  | `True` if both `a` and `b` are `True` |
| `a or b`   | `True` if at least one of `a` or `b` is `True` |

*Examples:*

In [4]:
# a and b reference the same object
a = [1,2]
b = a
a is b          # objects are identical, returns True

True

In [5]:
# a and b do NOT reference the same object, but contain
# identical elements.
b = a.copy()        # Use copy() method to create a copy
a is b              # returns False

False

In [6]:
# Check if collections contain the same elements
a == b              # returns True

True

In [7]:
# Check whether element is in collection
1 in a              # returns True

True

In [8]:
# Combine logical expressions using 'and'
1 in a and 2 in b   # returns True

True

We can also use the `in` operator to determine whether a key
is contained in a dictionary:

In [9]:
dct = {'institution': 'NHH'}
'institution' in dct        # prints True

True

In [10]:
# check whether a key is NOT in the dictionary
'course' not in dct         # prints True

True

As mentioned above, most objects evaluate to `True` or `False`
in an `if` statement:
```python
if obj:
    # do something if obj evaluates to True
```
The rules are quite intuitive: an object evaluates to `False` if

-   it has a numerical type and is `0` (or `0.0`, or complex `0+0j`)
-   it is an empty string `''`
-   it is an empty collection (tuple, list, dictionary, etc.)
-   it is of logical (boolean) type and has value `False`
-   it is `None`, a special built-in value used to denote that
    a variable does not reference anything.

In most other cases, an expression evaluates to `True`.

*Examples:*


In [11]:
# evaluate numerical variable
x = 0.0
if x:
    print('Value is non-zero')
else:
    print('Value is zero')

Value is zero


In [12]:
# Evaluate non-empty string
x = 'Hello'
if x:
    print('String is non-empty')
else:
    print('String is empty')

String is non-empty


In [13]:
# Check whether a collection (tuple, list, dictionary) is empty
# Create empty dictionary
dct = {}
if dct:
    print('Dictionary is non-empty')
else:
    print('Dictionary is empty')

Dictionary is empty


In [14]:
# Evaluate boolean variable
flag = True
if flag:
    print('Flag is True')
else:
    print('Flag is False')

Flag is True


The most important exception to the rule that objects intuitively
evaluate to `True` or `False` is the behavior of NumPy arrays:

In [15]:
import numpy as np

# Create array with 5 zeros
arr = np.zeros(5)
if arr:
    print('true!')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

As the error message indicates, NumPy requires you to be more specific
about what exactly should be tested.

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>
Check whether it is possible to perform the following comparisons and inspect their results.
<ol>
    <li>Define a list <tt>[1.0, 2.0]</tt> and a tuple <tt>(1.0, 2.0)</tt>, and check for 
        equality using <tt>==</tt>.</li>
    <li>Define a list <tt>[1.0, 2.0]</tt> and a NumPy array with elements <tt>[1.0, 2.0]</tt>, and check for equality using <tt>==</tt>.</li>
    <li>What does the expression <tt>'P' in 'Python'</tt> evaluate to? How about <tt>'Py' in 'Python'</tt>?</li> 
    <li>What does the expression <tt>'a' in ['a', 'b']</tt> evaluate to? 
        How about <tt>['a'] in ['a', 'b']</tt>?</li> 
    <li>What is the value of the expression <tt>1.0 == (1.0 + 1.0e-16)</tt>?</li>
</ol>
</div>
<span style="display: none;">YourTurnEnd</span>

In [9]:
#Task 1
lst = [1.0, 2.0]
tup = (1.0, 2.0)

In [10]:
lst == tup

False

In [12]:
import numpy as np
#Task 2
lst = [1.0, 2.0]
arr = np.array([1.0, 2.0])
lst == arr

array([ True,  True])

In [14]:
"P" in "Python"
"Py" in "Python"

True

In [ ]:
"a" in ["a", "b"]

True

In [ ]:
["a"] in ["a", "b"]

False

In [17]:
1.0 == (1.0 + 1.0e-16)

True

### Conditional expressions

Conditional expressions are more compact than conditional statements
and can be used to return a value depending
on some condition. A conditional expression takes three arguments using
the syntax

    <value if true> if <condition> else <value if false>

The value of this expression can be assigned to a variable,
passed to a function, etc.

To illustrate, imagine we have the following code:

In [16]:
x = 1

# Test whether x is divisible by 2 without remainder using
# the modulo operator %
if (x % 2) == 0:
    var = 'even'
else:
    var = 'odd'

This code sets the value of `var` to either `'even'` or `'odd'`,
depending on whether `x` is an even or odd integer. We can formulate
this more concisely using a conditional expression:

In [17]:
var = 'even' if (x % 2) == 0 else 'odd'

We can even directly print the value of this expression!

In [18]:
x = 1
print('even' if (x % 2) == 0 else 'odd')

odd


There is an even more compact notation that is often used to set a default value. Say that you write a function which takes a string argument and stores its value in the variable `argument` (we will study functions in the next lecture). 
This argument can potentially be an empty string, and in that case, you want to use a default value. 
In the function body, you could write code such as the following to achieve this:

In [19]:
# Assume empty string is passed as argument by the caller of a function
argument = ''
# Default value
default = 'default value'

# Check whether argument is empty, and if so, use the default value
if argument:
    var = argument
else:
    var = default

var

'default value'

This is admissible code but needlessly complicated. Using conditional expressions, you can abbreviate this as follows:

In [20]:
# Set default value if argument is empty
var = argument if argument else default

var

'default value'

This of course works as well, but there is an even shorter version using the logical `or` operator:

In [21]:
var = argument or default

var

'default value'

This logical `or` operator works as follows: if the left-hand-side operand evaluates to `True` (as a non-empty string does), the evaluation is aborted and this left-hand-side value is returned. If the left-hand-side operand evaluates to `False`, the right-hand-side operand is returned.

***
## Loops

### The `for` loop

Whenever we want to iterate over several items, we use the
`for` loop. The `for` loop in Python is particularly powerful
because it can "magically" iterate over all sorts of data,
not just integer ranges.

The standard use-case is to iterate over a set of integers:

In [22]:
# iterate over 0,...,3 and print each element
for i in range(4):
    print(i)

0
1
2
3


We use the built-in [`range()`](https://docs.python.org/3/library/functions.html#func-range)
function to define the sequence
of integers over which to loop. As usual in Python, the
last element is *not* included. We can explicitly specify
the start value and increment using the more advanced syntax
`range(start,stop,step)`:

In [18]:
# iterate over 1,3
for i in range(1, 4, 2):
    print(i)

1
3


Unlike with some other languages, we can directly
iterate over elements of a collection:

In [24]:
cities = ('Bergen', 'Oslo', 'Stavanger')
for city in cities:
    print(city)

Bergen
Oslo
Stavanger


We could of course alternatively iterate over indices
and extract the corresponding element, but there is no
need to:

In [25]:
# Needlessly complicated and non-Pythonic
cities = ('Bergen', 'Oslo', 'Stavanger')
for i in range(len(cities)):
    # print city at index i
    print(cities[i])

Bergen
Oslo
Stavanger


<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>
Write a <tt>for</tt> loop that prints the squares of all even numbers between 0 and 10 (inclusive). <i>Hint:</i> The exponentiation operator in Python is <tt>**</tt>.
</div>
<span style="display: none;">YourTurnEnd</span>

In [19]:
for x in range(0, 11, 2):
    print(x ** 2)

0
4
16
36
64
100


#### Looping over dictionaries

When looping over dictionaries, the default 
is to iterate over *keys*:

In [26]:
dct = {'key1': 'value1', 'key2': 'value2'}
for key in dct:
    print(key)

key1
key2


We can explicitly choose whether to iterate over keys, values, or both:

In [27]:
# iterate over keys, same as example above
for key in dct.keys():
    print(key)

key1
key2


In [28]:
# iterate over values
for value in dct.values():
    print(value)

value1
value2


In [29]:
# iterate over keys and values at the same time
# using the items() method
for key, value in dct.items():
    # use f-string to print key: value
    print(f'{key}: {value}')

key1: value1
key2: value2


Note that `items()` returns the key-value pairs as `tuples`,
so we need to unpack each tuple by writing `key, value`
as the running variables of the `for` loop.

### The `while` loop

Sometimes the set of items over which to iterate is not known ex ante,
and then we can instead use the `while` loop with a termination condition:

In [30]:
z = 1.001
i = 0

# How many iterations will be performed? Not obvious ex ante.
while z < 100.0:
    z = z*z + 0.234
    i = i + 1

# print number of iterations
print(f'loop terminated after {i} iterations; z = {z}')

loop terminated after 5 iterations; z = 129.58937197374684


<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>

Use the <tt>while</tt> loop to emulate a <tt>for</tt> loop: Iterate over the set of integers 0,...,4 and print the loop variable in each iteration.
</div>
<span style="display: none;">YourTurnEnd</span>

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [21]:
i = 0

while i < 5:
    print(i)
    i = i + 1

0
1
2
3
4


### Advanced looping

Oftentimes, we want to iterate over a list of items and
at the same time keep track of an item's index. We can
do this elegantly using the `enumerate()` function:

In [31]:
cities = ('Bergen', 'Oslo', 'Stavanger')

# Iterate over cities, keep track of index in variable i
for i, city in enumerate(cities):
    print(f'City {i}: {city}')

City 0: Bergen
City 1: Oslo
City 2: Stavanger


We can skip an iteration or terminate the loop using the
`continue` and `break` statements, respectively:

In [32]:
for city in cities:
    if city == 'Oslo':
        # skip to next iteration in case of Oslo
        continue
    print(city)

Bergen
Stavanger


In [33]:
for city in cities:
    if city == 'Bergen':
        # Terminate iteration as soon as we find Bergen
        print(f'Found {city}')
        break

Found Bergen


We often want to loop over multiple collections at once. This can be achieved in various ways, but if we are working with collections of equal length, we usually use the
[`zip()`](https://docs.python.org/3.13/library/functions.html#zip)
function.

Imagine we are given a list of regions and their capital cities and want to print each region together with its capital:

In [34]:
# List of capitals
capitals = ['Bergen', 'Stavanger', 'Trondheim']
# List of regions
regions = ['Vestland', 'Rogaland', 'Trøndelag']

# Iterate through capitals and regions in parallel
for c, r in zip(capitals, regions):
    print(f'The capital of {r} is {c}')

The capital of Vestland is Bergen
The capital of Rogaland is Stavanger
The capital of Trøndelag is Trondheim


In other programming languages, we would have likely used a running index instead, but this is unnecessary in Python:

In [35]:
# Alternative, non-Pythonic implementation
for i in range(len(capitals)):
    print(f'The capital of {regions[i]} is {capitals[i]}')

The capital of Vestland is Bergen
The capital of Rogaland is Stavanger
The capital of Trøndelag is Trondheim


<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>

Consider the following list of Nordic countries and their capitals:
<p>
<tt>capitals = ['Oslo', 'Stockholm', 'Copenhagen', 'Helsinki']</tt>
</p>
<p>
<tt>countries = ['Norway', 'Sweden', 'Denmark', 'Finland']</tt>
</p>

Using a <tt>for</tt> loop, create a dictionary that maps the country (the key)
to its capital (the value).
</div>
<span style="display: none;">YourTurnEnd</span>

In [2]:
# Task
capitals = ["Oslo", "Stockholm", "Copenhagen", "Helsinki"]
countries = ["Norway", "Sweden", "Denmark", "Finland"]

#Using a for lopp where key = country name, value = capital city
for co, ca in zip(countries, capitals):
    print(f"The capital of {co} is {ca}")

The capital of Norway is Oslo
The capital of Sweden is Stockholm
The capital of Denmark is Copenhagen
The capital of Finland is Helsinki


***
## List comprehensions

Python implements a powerful feature called _list comprehensions_ that can be
used to create collections such as tuples and lists without writing loop statements.

For example, imagine we want to create a list of squares
of the integers $0,\dots,4$. We can do this using a loop
and a list's `append()` method:

In [36]:
# Initialize empty list
squares = []

# Loop over integers 0,...,4
for i in range(5):
    # The power operator in Python is **
    squares.append(i**2)
squares

[0, 1, 4, 9, 16]

This is quite bloated and can be collapsed into a single
expression using a list comprehension:

In [37]:
squares = [i**2 for i in range(5)]
squares

[0, 1, 4, 9, 16]

If the desired result should be a `tuple`, we can instead write

In [38]:
squares = tuple(i**2 for i in range(5))
squares

(0, 1, 4, 9, 16)

Note that the `tuple()` syntax is mandatory: one cannot create a tuple using a list comprehension with only `()` as this returns a generator object instead:

In [39]:
# Wrong attempt to create a tuple from a list comprehension, returns generator
squares = (i**2 for i in range(5))
squares

<generator object <genexpr> at 0x7f70fd7f4ba0>

Alternatively, we can also create a dictionary using curly
braces and the syntax `{key: <expression> for ...}`:

In [40]:
squares = {i: i**2 for i in range(5)}
squares

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

List comprehensions can be nested and combined with
conditions to create almost arbitrarily complex expressions
(this doesn't mean that you should, though!)

In [41]:
# Create incomprehensible list comprehension.
# The modulo operator in Python is %
items = [i*j for i in range(5) if i % 2 == 0 for j in range(i)]
items

[0, 2, 0, 4, 8, 12]

Written out as two nested loops, this code is equivalent to

In [42]:
items = []
for i in range(5):
    if i % 2 == 0:
        for j in range(i):
            items.append(i*j)
items

[0, 2, 0, 4, 8, 12]

<div style="background-color: #c6dbef; color: #363636; padding: 0.8em 1em 0.5em 1em; border: 1pt solid #363636;">
<h3 style="font-weight: bold;">Your turn</h3>

Adapt the previous exercise mapping countries to their capitals: 
instead of using a loop, create the dictionary
mapping countries to their capitals using a <i>list comprehension</i>.
</div>
<span style="display: none;">YourTurnEnd</span>

In [3]:
country_to_capital = {country: capital for country, capital in zip(countries, capitals)}
country_to_capital

{'Norway': 'Oslo',
 'Sweden': 'Stockholm',
 'Denmark': 'Copenhagen',
 'Finland': 'Helsinki'}

***
## Optional exercises

These exercises are not meant to demonstrate the most efficient
use of Python, but to help you practice the material we have
studied above. In fact, you'd most likely *not* want to use the solutions presented here
in real code!

### Exercise 1: Approximate Euler's number
Euler's number is defined as
$$e = \lim_{n\to\infty} \left(1+\frac{1}{n}\right)^n$$

1.  Create a sequence of the approximations to $e$ for $n=10,20,30,\dots,100$
    using a list comprehension.
2.  Compute and print the approximation error for each of the elements.
    
    *Hint:* To get the built-in value for $e$, use
    the import statement

    ```python
    from math import e
    ```

In [4]:
from math import e

# 1) n values: 10, 20, ..., 100
n_values = range(10, 101, 10)

# 2) Approximations to e using a list comprehension
approximations = [(1 + 1/n)**n for n in n_values]

# 3) Print n, approximation, and error [approx - true e]
for n, approx in zip(n_values, approximations):
    error = abs(approx - e)
    print(f"n = {n:3d} approx = {approx:.10f} error = {error:.10f}")

n =  10 approx = 2.5937424601 error = 0.1245393684
n =  20 approx = 2.6532977051 error = 0.0649841233
n =  30 approx = 2.6743187759 error = 0.0439630526
n =  40 approx = 2.6850638384 error = 0.0332179901
n =  50 approx = 2.6915880291 error = 0.0266937994
n =  60 approx = 2.6959701393 error = 0.0223116891
n =  70 approx = 2.6991163710 error = 0.0191654575
n =  80 approx = 2.7014849408 error = 0.0167968877
n =  90 approx = 2.7033324611 error = 0.0149493674
n = 100 approx = 2.7048138294 error = 0.0134679990


### Exercise 2: Approximate the sum of a geometric series

Let $\alpha \in (0,1)$. The sum of the
geometric series $(1,\alpha,\alpha^2,\dots)$ is given by
$$\sigma = \sum_{i=0}^{\infty} \alpha^i = \frac{1}{1-\alpha}$$

Assume that $\alpha = 0.1$.
Write a loop that accumulates the values of the sequence
$(1,\alpha,\alpha^2,\dots)$ until the difference to the true
value is smaller than $1\times 10^{-8}$.
How many iterations does it take?

*Hint:* In Python (and many other languages) the floating-point
value $1\times10^{-8}$ is written as `1e-8`.

In [5]:
alpha = 0.1

true_sum = 1 / (1-alpha)    # exact value: 1 / 0.9 = 
approx_sum = 0.0            # running (partial) sum
term = 1.0                  # first term is alpha^0 = 1
iterations = 0

#Lopp until the approximation is within 1e-8 of the true value
while abs(true_sum - approx_sum) > 1e-8:
    approx_sum += term      # adding current term
    term *= alpha           # prepare next term: alpha^i -> alpha^(1+i)
    iterations += 1

print("Approximate sum:", approx_sum)
print("True sum       :", true_sum)
print("error          :", abs(true_sum - approx_sum))
print("Iterations     :", iterations) 

Approximate sum: 1.11111111
True sum       : 1.1111111111111112
error          : 1.1111112030448567e-09
Iterations     : 9


### Exercise 3: Diagonal and band matrices

Let `a` be a matrix of zeros with shape `(m,n)` with an integer data type:
```python
a = np.zeros((m,n), dtype=int)
```

1.  Set `m = n = 4`. Fill up the diagonal of `a` with ones so that it
    becomes an identity matrix. Verify that `np.identity()` gives the same result.
2.  Create a $4 \times 5$ matrix `b` of zeros. 
    Modify the main, first lower and
    first upper diagonals so that the resulting matrix looks like this,
    where omitted elements are zeros:
    $$
    \begin{bmatrix}
    1 & 2 &   &   & \\
    3 & 1 & 2 &   & \\
      & 3 & 1 & 2 & \\
      &   & 3 & 1 & 2
    \end{bmatrix}
    $$

    *Hint:* Use nested `for` loops to set the diagonal elements.

In [ ]:
import numpy as np

# Part 1: identify matrix
m = n = 4
a = np.zeros((m,n), dtype = int)

for i in range(m):
    for j in range(n):
        if i == j:
            a[i, j] = 1

print("Matrix a:")
print(a)
print("np.identity(4):")            #Verifying with numpy formula
print(np.identity(4, dtype = int))  #


Matrix a:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
np.identity(4):
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [11]:
# Part 2; 4x5 band matrix
rows = 4
cols = 5
b = np.zeros((rows, cols), dtype = int)

for i in range(rows):
    for j in range(cols):
        if i == j:              # The (main) diagonal
            b[i, j] = 1
        elif i == j + 1:        # First lower diagonal
            b[i, j] = 3
        elif j == i + 1:        # First upper diagonal
            b[i, j] = 2

print("Matrix b:")
print(b)
        

Matrix b:
[[1 2 0 0 0]
 [3 1 2 0 0]
 [0 3 1 2 0]
 [0 0 3 1 2]]


### Exercise 4: Triangular matrices

Let `a` be a matrix of zeros with shape `(m,n)` and integer data type:
```python
a = np.zeros((m,n), dtype=int)
```

Assume that `m = n = 4`. Using loops and `if` statements, modify the elements of `a`
to obtain the following upper-triangular matrix, where omitted elements
are set to zero:
$$
\begin{bmatrix}
1 & 2 & 3 & 4  \\
 & 5 & 6 & 7  \\
  & & 8 & 9 \\
  & & & 10 
\end{bmatrix}
$$

In [12]:
import numpy as np

m = n = 4
a = np.zeros((m, n), dtype = int)

value = 1               #next number to place

for i in range(m):
    for j in range(n):
        if j >= i:      #only on or above the main diagonal
            a[i, j] = value
            value += 1  #prepare next number

print(a)

[[ 1  2  3  4]
 [ 0  5  6  7]
 [ 0  0  8  9]
 [ 0  0  0 10]]


### Exercise 5: Binary search (advanced)

The [bisection method](https://en.wikipedia.org/wiki/Bisection_method)
can be used to find the root of a function
$f(x)$, i.e., the point $x_0$ such that $f(x_0) = 0$.
In this exercise, we will use the same algorithm
to find the interval of a strictly monotonic
sequence of numbers that brackets the value zero
(this is a [binary search algorithm](https://en.wikipedia.org/wiki/Binary_search_algorithm)
with approximate matching).

Assume that we have an array `x` of 11 increasing real numbers
given by

In [ ]:
import numpy as np

# Given data (part of the solution under)
x = np.linspace(-0.5, 1.0, 11)
x

array([-0.5 , -0.35, -0.2 , -0.05,  0.1 ,  0.25,  0.4 ,  0.55,  0.7 ,
        0.85,  1.  ])

Write code that identifies the bracketing interval
(in this case [-0.05,0.1]) using the following algorithm:

1.  Initialize the index of the bracket lower bound to
    `lbound=0` and the index of the bracket upper
    bound to `ubound=len(x)-1`.
2.  Compute the midpoint between these two indices (rounded to
    the nearest integer), `mid = (ubound + lbound) // 2`.
    
    *Hint:* The operator `//` truncates the result of a division
    to the nearest integer.
3.  Inspect `x[mid]`, the value at index `mid`. If `x[mid]`
    has the same sign as `x[ubound]`, update the upper bound,
    `ubound=mid`. Otherwise, update the lower bound.
4.  Continue until `ubound = lbound + 1`, i.e., until you
    have found the bracket `x[lbound] <= 0 < x[ubound]`.

In [14]:
import numpy as np

# Given data (part of the solution under)
x = np.linspace(-0.5, 1.0, 11)
x

# 1) Initial indices for the bracket
lbound = 0
ubound = len(x) - 1

# 2-4) binary search for indices such that x[bound] <= 0 < x[bound]
while ubound > lbound + 1:
    # 2) midtpoint (integer index)
    mid = (lbound + ubound) // 2

    # 3) check the sign of x[mid] vs x[ubound]
    if x[mid] * x[ubound] > 0:
        #same sign as x[ubound] -> move upper bound, down
        ubound = mid
    else:
        #different sign (or zero) -> move lower bound up
        lbound = mid

print("x =", x)
print("lbound index", lbound, "value:", x[lbound])
print("ubound index", ubound, "value:", x[ubound])

x = [-0.5  -0.35 -0.2  -0.05  0.1   0.25  0.4   0.55  0.7   0.85  1.  ]
lbound index 3 value: -0.050000000000000044
ubound index 4 value: 0.09999999999999998


***
## Solutions

### Solution for exercise 1

In [44]:
# Compute approximation for n = 10, 20,..., 100
euler_approx = [(1.0+1.0/i)**i for i in range(10,101,10)]
print('Approximate values')
print(euler_approx)

# import 'correct' value
from math import e

# We need to subtract e from each element to get the approximation error
euler_error = [approx - e for approx in euler_approx]
print('Approximation error:')
print(euler_error)

Approximate values
[2.5937424601000023, 2.653297705144422, 2.6743187758703026, 2.685063838389963, 2.691588029073608, 2.6959701393302162, 2.6991163709761854, 2.7014849407533275, 2.703332461058186, 2.7048138294215285]
Approximation error:
[-0.12453936835904278, -0.06498412331462289, -0.043963052588742446, -0.03321799006908188, -0.026693799385437256, -0.02231168912882886, -0.019165457482859694, -0.016796887705717634, -0.01494936740085917, -0.01346799903751661]


### Solution for exercise 2

We don't know how many iterations we will need to reach the required
tolerance of $1\times10^{-8}$, so this is a good opportunity
to use a `while` loop.

In [45]:
# Convergence tolerance
tol = 1e-8
alpha = 0.1
# The correct value
sigma_exact = 1.0/(1.0 - alpha)

# keep track of number of iterations
n = 0

# Initialise approximated sum
sigma = 0.0

# Iterate until absolute difference is smaller than tolerance level.
# The built-in function abs() returns the absolute value.

while abs(sigma - sigma_exact) > tol:
    # We can combine addition and assignment into a single operator +=
    # This is equivalent to
    #   sigma = sigma + alpha**n
    sigma += alpha**n
    # Increment exponent
    n += 1

print(f'Number of iterations: {n}, approx. sum: {sigma:.8f}')

Number of iterations: 9, approx. sum: 1.11111111


### Solution for exercise 3

For the first part, we need to loop over the diagonal elements and overwrite
the zeros with ones:

In [46]:
# Part 1: create identity matrix

import numpy as np

n = 4
a = np.zeros((n,n), dtype=int)

# loop over diagonal elements, set them to 1
for i in range(n):
    a[i,i] = 1

# print identity matrix
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

You can get the same result using NumPy's `np.identity()` function:

In [47]:
n = 4
np.identity(n, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

For the second part, we need nested loops over rows and columns and we check at each 
position $(i,j)$ whether it is on the main diagonal, or on the first upper 
or lower diagonal.

In [48]:
# Part 2: create band matrix

import numpy as np

m = 4
n = 5

b = np.zeros((m,n), dtype=int)

# loop over rows
for i in range(m):
    # loop over columns
    for j in range(n):
        if i == j:
            # main diagonal element
            b[i,j] = 1
        elif i == (j - 1):
            # upper diagonal element
            b[i,j] = 2
        elif i == (j + 1):
            # lower diagonal element
            b[i,j] = 3

# print final matrix
b

array([[1, 2, 0, 0, 0],
       [3, 1, 2, 0, 0],
       [0, 3, 1, 2, 0],
       [0, 0, 3, 1, 2]])

### Solution for exercise 4

We solve this exercise using two nested `for` loops, the first over rows,
the second over columns:

In [49]:
import numpy as np 

m = 4
n = 4

a = np.zeros((m,n), dtype=int)

# keep track of value to be inserted
value = 1

# loop over rows
for i in range(m):
    # loop over columns
    for j in range(i, n):
        a[i,j] = value
        # increment value for next matching element
        value += 1

# print final matrix
a


array([[ 1,  2,  3,  4],
       [ 0,  5,  6,  7],
       [ 0,  0,  8,  9],
       [ 0,  0,  0, 10]])

Note that the loop over columns uses the current row index as the lower bound, since
we never need to insert anything at element $(i,j)$ if $j < i$.

### Solution for exercise 5

To complete the exercise, all you have to do is to translate
the algorithm given in the exercise into code.

Since we don't know how many iterations it takes to find the bracket,
we use a `while` loop that continues as long
as `lbound` and `ubound` are more than 1 apart.

In [50]:
import numpy as np

# Given array of increasing numbers
x = np.linspace(-0.5, 1.0, 11)


lbound = 0
ubound = len(x) - 1

while ubound > (lbound + 1):
    # Index of mid point. Indices have to be integers, so
    # we need to truncate the division result to an integer.
    mid = (ubound + lbound) // 2

    if (x[mid] * x[ubound]) > 0.0:
        # x[mid] and x[ubound] have same sign!
        ubound = mid
        print(f'Setting upper bound index to {ubound}')
    else:
        # x[mid] and x[lbound] have the same sign
        # or at least one of them is zero
        lbound = mid
        print(f'Setting lower bound index to {lbound}')

print(f'Value at lower bound: {x[lbound]:.4g}')
print(f'Value at upper bound: {x[ubound]:.4g}')

Setting upper bound index to 5
Setting lower bound index to 2
Setting lower bound index to 3
Setting upper bound index to 4
Value at lower bound: -0.05
Value at upper bound: 0.1


In this implementation, we use the fact that two non-zero real numbers $a$
and $b$ have the same sign whenever $a \cdot b > 0$.